create table if not exists events (
  "id" character varying not null primary key,
  "name" character varying not null,
  "location" character varying,
  "startTime" timestamp,
  "endTime" timestamp,
  "maxCapacity" integer,
  "createdAt" timestamp not null default now(),
  "updatedAt" timestamp not null default now() 
);

create table if not exists attendees(
  "id" bigint primary key generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 999999999 cache 1 ),
  "name" character varying not null,
  "email" character varying not null,
  "eventId" character varying,
  foreign key ("eventId") references events (id) on delete cascade 
);